# Generated by Django 2.2.13 on 2021-06-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
