# Generated by Django 3.2.4 on 2021-07-05 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20210623_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='joining',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
